#!/bin/bash

echo ""
echo "=========================================="
echo "       CYBERSECURITY DEMONSTRATION"
echo "=========================================="
echo ""
echo "This file was downloaded from a link."
echo ""
echo "In a real attack, an attacker could"
echo "attempt to deliver malicious software."
echo ""
echo "This file is completely harmless."
echo "It does NOT modify the system."
echo "It does NOT create persistence."
echo "It does NOT communicate with an attacker."
echo ""
echo "The important lesson:"
echo ""
echo "A suspicious download should NOT be opened"
echo "just because it came from an email or message."
echo ""
echo "=========================================="